// ============================================================
// DATA - ข้อมูลบัญชีรายชื่อกำลังพล ร.19 พัน.1
// ============================================================

const DEFAULT_DATA = {

    // ===== PAGE 1: นายทหารสัญญาบัตร =====
    page1: {
        title: 'บัญชีรายชื่อนายทหารสัญญาบัตร',
        subtitle: 'หน่วย ร.19 พัน.1',
        personnel: [
            { id: 'P1-001', rank: 'พ.ท.', firstName: 'เอกพจน์', lastName: 'นามถาวร', taxStatus: '' },
            { id: 'P1-002', rank: 'ร.อ.', firstName: 'รัฐเศรษฐ์', lastName: 'วงษ์ขันธ์', taxStatus: '' },
            { id: 'P1-003', rank: 'ร.อ.', firstName: 'วิฑูรย์', lastName: 'โสขุมา', taxStatus: '' },
            { id: 'P1-004', rank: 'ร.ต.', firstName: 'ณัฐพงค์', lastName: 'ตั้งวงค์', taxStatus: '' },
            { id: 'P1-005', rank: 'ร.อ.', firstName: 'อนุชา', lastName: 'ม่วงนนทะศรี', taxStatus: '' },
            { id: 'P1-006', rank: 'ร.ท.', firstName: 'พงศกร', lastName: 'สร้อยฉวี', taxStatus: '' },
            { id: 'P1-007', rank: 'ร.ท.', firstName: 'ปภพ', lastName: 'ศรีสังวาลย์', taxStatus: '' },
            { id: 'P1-008', rank: 'ร.ท.', firstName: 'ณัฐวรรธน์', lastName: 'เสือเผือก', taxStatus: '' },
            { id: 'P1-009', rank: 'ร.ท.', firstName: 'ปฏิพัฒน์', lastName: 'ชมเจริญ', taxStatus: '' },
            { id: 'P1-010', rank: 'ร.ต.', firstName: 'อนุสรณ์', lastName: 'นุ่มไพร', taxStatus: '' },
            { id: 'P1-011', rank: 'ร.ต.', firstName: 'อธิพงษ์', lastName: 'ป้องเรือ', taxStatus: '' },
            { id: 'P1-012', rank: 'ร.ต.', firstName: 'สุภเดช', lastName: 'ทรงประสพ', taxStatus: '' },
            { id: 'P1-013', rank: 'ร.ต.', firstName: 'กรวิชญ์', lastName: 'แสงจันทร์', taxStatus: '' },
            { id: 'P1-014', rank: 'ร.ต.', firstName: 'เอกดนัย', lastName: 'ทองกุล', taxStatus: '' },
            { id: 'P1-015', rank: 'ร.ต.', firstName: 'บรรฑูรย์', lastName: 'พุ่มพวง', taxStatus: '' },
            { id: 'P1-016', rank: 'ร.ต.', firstName: 'พจน์', lastName: 'สิงหพันธุ์', taxStatus: '' },
            { id: 'P1-017', rank: 'ร.ท.', firstName: 'ไชยยันต์', lastName: 'จันทวัน', taxStatus: '' },
            { id: 'P1-018', rank: 'ร.ต.', firstName: 'อิทธิพันธ์', lastName: 'ทองทิพยา', taxStatus: '' },
            { id: 'P1-019', rank: 'ร.อ.', firstName: 'กรันชัย', lastName: 'ภควัฒน์นานนท์', taxStatus: '' },
            { id: 'P1-020', rank: 'ร.ต.', firstName: 'ปวริศ', lastName: 'พรพิจิตรทรัพย์', taxStatus: '' },
            { id: 'P1-021', rank: 'ร.ท.', firstName: 'ชัชวาลย์', lastName: 'เกวิโก', taxStatus: '' },
            { id: 'P1-022', rank: 'ร.ท.', firstName: 'พลวรรธน์', lastName: 'พรมบุตร', taxStatus: '' },
            { id: 'P1-023', rank: 'ร.อ.', firstName: 'สุชาติ', lastName: 'สุขสวัสดิ์', taxStatus: '' },
            { id: 'P1-024', rank: 'ร.ท.', firstName: 'สุทธิรักษ์', lastName: 'อ้นชู', taxStatus: '' }
        ]
    },

    // ===== PAGE 2: นายทหารประทวน ร้อย.1 =====
    page2: {
        title: 'บัญชีรายชื่อนายทหารประทวน',
        subtitle: 'หน่วย ร.19 พัน.1 ร้อย.1',
        personnel: [
            { id: 'P2-001', rank: 'จ.ส.อ.(พ)', firstName: 'พิสิษฐ์', lastName: 'ช้างเชื้อวงษ์', taxStatus: '' },
            { id: 'P2-002', rank: 'จ.ส.อ.', firstName: 'จักรกฤษ', lastName: 'สำเร็จทรัพย์', taxStatus: '' },
            { id: 'P2-003', rank: 'จ.ส.อ.', firstName: 'กัณพัฒน์', lastName: 'สัมฤทธิ์ผล', taxStatus: '' },
            { id: 'P2-004', rank: 'จ.ส.อ.', firstName: 'ธนพล', lastName: 'ประทุมสูตร', taxStatus: '' },
            { id: 'P2-005', rank: 'จ.ส.อ.', firstName: 'บุญเหนือ', lastName: 'บุญสิน', taxStatus: '' },
            { id: 'P2-006', rank: 'จ.ส.อ.(พ)', firstName: 'บุญเยี่ยม', lastName: 'โสชาติ', taxStatus: '' },
            { id: 'P2-007', rank: 'จ.ส.อ.(พ)', firstName: 'อภิชัย', lastName: 'มุ่งชัย', taxStatus: '' },
            { id: 'P2-008', rank: 'จ.ส.อ.', firstName: 'อาคม', lastName: 'สินแจ่ม', taxStatus: '' },
            { id: 'P2-009', rank: 'จ.ส.อ.', firstName: 'บุญรุ่ง', lastName: 'ชิวปรีชา', taxStatus: '' },
            { id: 'P2-010', rank: 'จ.ส.อ.', firstName: 'อดิศร', lastName: 'แสงศรี', taxStatus: '' },
            { id: 'P2-011', rank: 'จ.ส.อ.', firstName: 'ธันพิพัฒน์', lastName: 'โกมลวานิชย์', taxStatus: '' },
            { id: 'P2-012', rank: 'ส.อ.', firstName: 'สันติสุข', lastName: 'อุตส่าห์', taxStatus: '' },
            { id: 'P2-013', rank: 'ส.อ.', firstName: 'ไกรวิทย์', lastName: 'มาตจรัญ', taxStatus: '' },
            { id: 'P2-014', rank: 'ส.อ.', firstName: 'นครินทร์', lastName: 'สังข์ศรี', taxStatus: '' },
            { id: 'P2-015', rank: 'ส.อ.', firstName: 'กิติพงษ์', lastName: 'ไชยรินทร์', taxStatus: '' },
            { id: 'P2-016', rank: 'ส.อ.', firstName: 'ธีรศักดิ์', lastName: 'ทิมอ่อน', taxStatus: '' },
            { id: 'P2-017', rank: 'ส.อ.', firstName: 'ภูษิต', lastName: 'เพ็ชรอาบ', taxStatus: '' },
            { id: 'P2-018', rank: 'ส.ท.', firstName: 'อาทิตย์', lastName: 'แสงประโคน', taxStatus: '' },
            { id: 'P2-019', rank: 'ส.อ.', firstName: 'รังสรรค์', lastName: 'อุบลธรรม', taxStatus: '' },
            { id: 'P2-020', rank: 'ส.อ.', firstName: 'ยศพนธ์', lastName: 'แจะจันทร์', taxStatus: '' },
            { id: 'P2-021', rank: 'จ.ส.อ.(พ)', firstName: 'ประสิทธิ์', lastName: 'กุดขุนทด', taxStatus: '' },
            { id: 'P2-022', rank: 'ส.อ.', firstName: 'พัชระ', lastName: 'กล่ำเอม', taxStatus: '' },
            { id: 'P2-023', rank: 'ส.อ.', firstName: 'ปรัชญา', lastName: 'ปุญญฤทธิ์', taxStatus: '' },
            { id: 'P2-024', rank: 'จ.ส.อ.', firstName: 'เกียรติพงษ์', lastName: 'ไสว', taxStatus: '' },
            { id: 'P2-025', rank: 'จ.ส.อ.', firstName: 'ประสาน', lastName: 'นิลประดับ', taxStatus: '' },
            { id: 'P2-026', rank: 'ส.อ.', firstName: 'บุญทวี', lastName: 'บุญฤทธิ์เดโชชัย', taxStatus: '' },
            { id: 'P2-027', rank: 'ส.ท.', firstName: 'ธนานุวัฒน์', lastName: 'เพียโคตร', taxStatus: '' },
            { id: 'P2-028', rank: 'จ.ส.อ.', firstName: 'เอกนรินทร์', lastName: 'นิลเนตร', taxStatus: '' },
            { id: 'P2-029', rank: 'จ.ส.อ.', firstName: 'เสฏฐวุฒิ', lastName: 'สุกใส', taxStatus: '' },
            { id: 'P2-030', rank: 'ส.อ.', firstName: 'นราธิป', lastName: 'ลาภมาก', taxStatus: '' },
            { id: 'P2-031', rank: 'ส.ท.', firstName: 'วิศิษฏิ์', lastName: 'จิ้วไม้แดง', taxStatus: '' },
            { id: 'P2-032', rank: 'ส.ท.', firstName: 'สหรัฐ', lastName: 'มูลศิติ', taxStatus: '' },
            { id: 'P2-033', rank: 'ส.อ.', firstName: 'ณรงค์ศักดิ์', lastName: 'ดวงแก้ว', taxStatus: '' },
            { id: 'P2-034', rank: 'ส.ต.', firstName: 'ผไท', lastName: 'ทัพลา', taxStatus: '' },
            { id: 'P2-035', rank: 'ส.ต.', firstName: 'ภาสกร', lastName: 'บุญตรี', taxStatus: '' },
            { id: 'P2-036', rank: 'ส.ท.', firstName: 'ศักดิ์สิทธิ์', lastName: 'วงค์สว่าง', taxStatus: '' },
            { id: 'P2-037', rank: 'จ.ส.อ.', firstName: 'อิทธิพล', lastName: 'บุญชอบ', taxStatus: '' },
            { id: 'P2-038', rank: 'จ.ส.อ.', firstName: 'พิทยา', lastName: 'พินทา', taxStatus: '' },
            { id: 'P2-039', rank: 'จ.ส.อ.', firstName: 'ชัย', lastName: 'แก้วม่วงมัน', taxStatus: '' },
            { id: 'P2-040', rank: 'ส.อ.', firstName: 'เดชา', lastName: 'บัวนวน', taxStatus: '' },
            { id: 'P2-041', rank: 'จ.ส.อ.', firstName: 'ทนากร', lastName: 'โสจันทร์', taxStatus: '' },
            { id: 'P2-042', rank: 'จ.ส.อ.', firstName: 'บุญโฮม', lastName: 'แสงสุวรรณดี', taxStatus: '' },
            { id: 'P2-043', rank: 'ส.อ.', firstName: 'นพรัตน์', lastName: 'เหมือนมิ่ง', taxStatus: '' },
            { id: 'P2-044', rank: 'ส.อ.', firstName: 'กฤษดา', lastName: 'บุญเจริญ', taxStatus: '' },
            { id: 'P2-045', rank: 'จ.ส.ต.', firstName: 'สิทธิพันธ์', lastName: 'จันทวาท', taxStatus: '' }
        ]
    },

    // ===== PAGE 3: นายทหารประทวน ร้อย.อวบ.ที่ 2 =====
    page3: {
        title: 'บัญชีรายชื่อนายทหารประทวน',
        subtitle: 'หน่วย ร.19 พัน.1 ร้อย.อวบ.ที่ 2',
        personnel: [
            { id: 'P3-001', rank: 'จ.ส.อ.(พ)', firstName: 'สมคิด', lastName: 'แก้ววันนา', taxStatus: '' },
            { id: 'P3-002', rank: 'จ.ส.อ.', firstName: 'จีรวัฒน์', lastName: 'แก้วชมภู', taxStatus: '' },
            { id: 'P3-003', rank: 'จ.ส.อ.', firstName: 'พรชัย', lastName: 'วงศ์ทอง', taxStatus: '' },
            { id: 'P3-004', rank: 'จ.ส.อ.(พ.)', firstName: 'วุฒิชัย', lastName: 'ประเสริฐสังข์', taxStatus: '' },
            { id: 'P3-005', rank: 'จ.ส.อ.', firstName: 'ไพฑูลย์', lastName: 'ชัยสิทธิ์', taxStatus: '' },
            { id: 'P3-006', rank: 'จ.ส.อ.', firstName: 'เมธา', lastName: 'เสนานนท์', taxStatus: '' },
            { id: 'P3-007', rank: 'ส.อ.', firstName: 'อานนท์', lastName: 'นิลปั่น', taxStatus: '' },
            { id: 'P3-008', rank: 'จ.ส.อ.', firstName: 'นฤดล', lastName: 'ขาวสุข', taxStatus: '' },
            { id: 'P3-009', rank: 'จ.ส.ต.', firstName: 'เสกสรร', lastName: 'ภูเบ้าทอง', taxStatus: '' },
            { id: 'P3-010', rank: 'จ.ส.อ.', firstName: 'ธีรพันธ์', lastName: 'ไชยปัญญา', taxStatus: '' },
            { id: 'P3-011', rank: 'จ.ส.อ.(พ.)', firstName: 'สมเดช', lastName: 'ทองมณโฑ', taxStatus: '' },
            { id: 'P3-012', rank: 'ส.อ.', firstName: 'บำรุงราษฎร์', lastName: 'ไชยเวช', taxStatus: '' },
            { id: 'P3-013', rank: 'ส.อ.', firstName: 'กฤษนัย', lastName: 'งึ้มนันใจ', taxStatus: '' },
            { id: 'P3-014', rank: 'จ.ส.ต.', firstName: 'พีรพงค์', lastName: 'ชุ่มชื่น', taxStatus: '' },
            { id: 'P3-015', rank: 'ส.อ.', firstName: 'ทัศนัย', lastName: 'โม๊ะต๊ะ', taxStatus: '' },
            { id: 'P3-016', rank: 'จ.ส.อ.(พ)', firstName: 'ณรงค์เดช', lastName: 'มงคลเจริญ', taxStatus: '' },
            { id: 'P3-017', rank: 'จ.ส.อ.(พ)', firstName: 'สินชัย', lastName: 'ขันทอง', taxStatus: '' },
            { id: 'P3-018', rank: 'จ.ส.อ.', firstName: 'เบญจรงค์', lastName: 'กุลกรินีธรรม', taxStatus: '' },
            { id: 'P3-019', rank: 'ส.อ.', firstName: 'สมพร', lastName: 'เพชรรักษ์', taxStatus: '' },
            { id: 'P3-020', rank: 'จ.ส.อ.', firstName: 'สิริชัย', lastName: 'ทะนนท์', taxStatus: '' },
            { id: 'P3-021', rank: 'ส.ท.', firstName: 'ถิรวัฒน์', lastName: 'ทวีวงค์', taxStatus: '' },
            { id: 'P3-022', rank: 'ส.ท.', firstName: 'สิทธิชัย', lastName: 'อินทร์รัตน์', taxStatus: '' },
            { id: 'P3-023', rank: 'ส.อ.', firstName: 'ศรพิทักษ์', lastName: 'จัดนอก', taxStatus: '' },
            { id: 'P3-024', rank: 'ส.อ.', firstName: 'ไพศาล', lastName: 'แพงมี', taxStatus: '' },
            { id: 'P3-025', rank: 'ส.อ.', firstName: 'กิตติชัย', lastName: 'รุจิเรขวัตร', taxStatus: '' },
            { id: 'P3-026', rank: 'ส.ท.', firstName: 'อนุชิต', lastName: 'บุญอารีย์', taxStatus: '' },
            { id: 'P3-027', rank: 'ส.ท.', firstName: 'สรธัญ', lastName: 'สอนศรี', taxStatus: '' },
            { id: 'P3-028', rank: 'ส.ท.', firstName: 'ปวีณ', lastName: 'นามสมมิตร', taxStatus: '' },
            { id: 'P3-029', rank: 'ส.ท.', firstName: 'ศุภกร', lastName: 'สิงโต', taxStatus: '' },
            { id: 'P3-030', rank: 'ส.อ.', firstName: 'ปณิธาน', lastName: 'จันทร์ขอนแก่น', taxStatus: '' },
            { id: 'P3-031', rank: 'จ.ส.ต.', firstName: 'อัครวุฒ', lastName: 'สุภาพจน์', taxStatus: '' },
            { id: 'P3-032', rank: 'ส.ต.', firstName: 'กฤษณะ', lastName: 'พร้อมไธสงค์', taxStatus: '' },
            { id: 'P3-033', rank: 'ส.ต.', firstName: 'ธันยากร', lastName: 'คุ้มยวง', taxStatus: '' },
            { id: 'P3-034', rank: 'ส.ต.', firstName: 'ภัทรนันท์', lastName: 'สัตนาโค', taxStatus: '' },
            { id: 'P3-035', rank: 'ส.อ.', firstName: 'วิโรจน์', lastName: 'โชติขุนทด', taxStatus: '' },
            { id: 'P3-036', rank: 'จ.ส.อ.', firstName: 'นนทวัฒน์', lastName: 'โทแหล่ง', taxStatus: '' },
            { id: 'P3-037', rank: 'จ.ส.อ.', firstName: 'ธรนันท์', lastName: 'อนันต์สุข', taxStatus: '' },
            { id: 'P3-038', rank: 'ส.อ.', firstName: 'ศุภชัย', lastName: 'ศรียางนอก', taxStatus: '' },
            { id: 'P3-039', rank: 'จ.ส.อ.', firstName: 'เอกสิทธิ์', lastName: 'วิไลสิทธิ์', taxStatus: '' },
            { id: 'P3-040', rank: 'จ.ส.อ.', firstName: 'ศักรินทร์', lastName: 'สามิภักดิ์', taxStatus: '' },
            { id: 'P3-041', rank: 'จ.ส.อ.', firstName: 'ปริญญา', lastName: 'พระวิวงศ์', taxStatus: '' }
        ]
    },

    // ===== PAGE 4: นายทหารประทวน ร้อย.อวบ.ที่ 3 =====
    page4: {
        title: 'บัญชีรายชื่อนายทหารประทวน',
        subtitle: 'หน่วย ร.19 พัน.1 ร้อย.อวบ.ที่ 3',
        personnel: [
            { id: 'P4-001', rank: 'จ.ส.อ.(พ)', firstName: 'สวัสดิ์', lastName: 'เพ็งพลา', taxStatus: '' },
            { id: 'P4-002', rank: 'ส.ต.', firstName: 'มลฑกัณย์', lastName: 'บุตรแสน', taxStatus: '' },
            { id: 'P4-003', rank: 'จ.ส.อ.', firstName: 'พงศ์ดนัย', lastName: 'จันทะแก้ว', taxStatus: '' },
            { id: 'P4-004', rank: 'จ.ส.อ.', firstName: 'ประพล', lastName: 'ทับย้อย', taxStatus: '' },
            { id: 'P4-005', rank: 'จ.ส.อ.', firstName: 'กฤษชัย', lastName: 'คงพันธ์', taxStatus: '' },
            { id: 'P4-006', rank: 'จ.ส.อ.(พ)', firstName: 'สามารถ', lastName: 'สังข์ทอง', taxStatus: '' },
            { id: 'P4-007', rank: 'จ.ส.อ.(พ)', firstName: 'ธีระ', lastName: 'หมวกเพ็ชร', taxStatus: '' },
            { id: 'P4-008', rank: 'ส.อ.', firstName: 'ปรมัตถ์', lastName: 'มูลมา', taxStatus: '' },
            { id: 'P4-009', rank: 'จ.ส.อ.', firstName: 'ชัชวาลย์', lastName: 'คงกลาง', taxStatus: '' },
            { id: 'P4-010', rank: 'จ.ส.อ.', firstName: 'ศัตรูพ่าย', lastName: 'ศรีสม', taxStatus: '' },
            { id: 'P4-011', rank: 'ส.อ.', firstName: 'ศุภวิชญ์', lastName: 'ฉันทะกูล', taxStatus: '' },
            { id: 'P4-012', rank: 'ส.อ.', firstName: 'ธนโชติ', lastName: 'พันธมัง', taxStatus: '' },
            { id: 'P4-013', rank: 'ส.อ.', firstName: 'วทันย์', lastName: 'กลมกล่อมดี', taxStatus: '' },
            { id: 'P4-014', rank: 'ส.อ.', firstName: 'ณัฐวุฒิ', lastName: 'สีนวน', taxStatus: '' },
            { id: 'P4-015', rank: 'ส.อ.', firstName: 'ภุมมา', lastName: 'ทองแดง', taxStatus: '' },
            { id: 'P4-016', rank: 'จ.ส.อ.', firstName: 'บำรุง', lastName: 'จันทบูรณ์', taxStatus: '' },
            { id: 'P4-017', rank: 'จ.ส.อ.', firstName: 'นพดล', lastName: 'จุ้ยใจเหิม', taxStatus: '' },
            { id: 'P4-018', rank: 'จ.ส.อ.', firstName: 'เกรียงไกร', lastName: 'แก้วธานี', taxStatus: '' },
            { id: 'P4-019', rank: 'จ.ส.ท.', firstName: 'วุฒิชัย', lastName: 'เดชเชียร', taxStatus: '' },
            { id: 'P4-020', rank: 'ส.อ.', firstName: 'อรรถสิทธิ์', lastName: 'ทองหล่อ', taxStatus: '' },
            { id: 'P4-021', rank: 'ส.อ.', firstName: 'ธีรภัทร์', lastName: 'สังข์ทอง', taxStatus: '' },
            { id: 'P4-022', rank: 'จ.ส.อ.', firstName: 'บัญชา', lastName: 'ดาวประกายสี', taxStatus: '' },
            { id: 'P4-023', rank: 'จ.ส.อ.', firstName: 'เสรี', lastName: 'พรหมมา', taxStatus: '' },
            { id: 'P4-024', rank: 'ส.อ.', firstName: 'อัศนัย', lastName: 'นุ่มเนียม', taxStatus: '' },
            { id: 'P4-025', rank: 'ส.อ.', firstName: 'เสถียรพงษ์', lastName: 'อารีย์', taxStatus: '' },
            { id: 'P4-026', rank: 'ส.ท.', firstName: 'สิทธิชัย', lastName: 'อัจฉฤกษ์', taxStatus: '' },
            { id: 'P4-027', rank: 'ส.ท.', firstName: 'ณัฐพงษ์', lastName: 'สังฝาง', taxStatus: '' },
            { id: 'P4-028', rank: 'ส.ท.', firstName: 'สมคิด', lastName: 'มิถุนาวงศ์', taxStatus: '' },
            { id: 'P4-029', rank: 'จ.ส.อ.(พ)', firstName: 'ฉัตรชัย', lastName: 'ปัญจาสุธารส', taxStatus: '' },
            { id: 'P4-030', rank: 'ส.อ.', firstName: 'ธีระวิทย์', lastName: 'จันทร์ไหม', taxStatus: '' },
            { id: 'P4-031', rank: 'จ.ส.อ.', firstName: 'คมสันต์', lastName: 'แก้วคำปอด', taxStatus: '' },
            { id: 'P4-032', rank: 'จ.ส.อ.', firstName: 'กอล์ฟ', lastName: 'ศรีพงษ์', taxStatus: '' },
            { id: 'P4-033', rank: 'ส.อ.', firstName: 'จีระพงค์', lastName: 'แดงไฝ', taxStatus: '' },
            { id: 'P4-034', rank: 'ส.อ.', firstName: 'วิทวัส', lastName: 'ดีเดช', taxStatus: '' },
            { id: 'P4-035', rank: 'ส.อ.', firstName: 'สุทธิพงศ์', lastName: 'สุขศิริ', taxStatus: '' },
            { id: 'P4-036', rank: 'จ.ส.อ.', firstName: 'ทองสุข', lastName: 'สีหาบุตร', taxStatus: '' },
            { id: 'P4-037', rank: 'ส.อ.', firstName: 'สิทธิชัย', lastName: 'ศรีทอง', taxStatus: '' },
            { id: 'P4-038', rank: 'จ.ส.อ.(พ)', firstName: 'สำรวย', lastName: 'อ่อนตีบ', taxStatus: '' },
            { id: 'P4-039', rank: 'จ.ส.อ.', firstName: 'นัฐพงศ์', lastName: 'ปกครอง', taxStatus: '' },
            { id: 'P4-040', rank: 'ส.อ.', firstName: 'อดิศักดิ์', lastName: 'ทานะเวช', taxStatus: '' },
            { id: 'P4-041', rank: 'ส.อ.', firstName: 'นพดล', lastName: 'ชูกำลัง', taxStatus: '' },
            { id: 'P4-042', rank: 'ส.อ.', firstName: 'สรศักดิ์', lastName: 'นิลบดี', taxStatus: '' },
            { id: 'P4-043', rank: 'จ.ส.อ.', firstName: 'ทยากร', lastName: 'ภัทรปิยทัศน์', taxStatus: '' },
            { id: 'P4-044', rank: 'จ.ส.อ.', firstName: 'ทรงพล', lastName: 'อินรีย์', taxStatus: '' },
            { id: 'P4-045', rank: 'ส.อ.', firstName: 'ตระกูลฉัตร', lastName: 'ทองใบ', taxStatus: '' },
            { id: 'P4-046', rank: 'ส.อ.', firstName: 'รัฐนันท์', lastName: 'รามัญ', taxStatus: '' },
            { id: 'P4-047', rank: 'ส.อ.', firstName: 'รัชชานนท์', lastName: 'วงษาโสม', taxStatus: '' }
        ]
    },

    // ===== PAGE 5: นายทหารประทวน ร้อย.บก. =====
    page5: {
        title: 'บัญชีรายชื่อนายทหารประทวน',
        subtitle: 'ร้อย.บก.ร.19 พัน.1',
        personnel: [
            { id: 'P5-001', rank: 'จ.ส.อ.(พ)', firstName: 'อิทธิ', lastName: 'กลิ่นหอม', taxStatus: '' },
            { id: 'P5-002', rank: 'จ.ส.อ.', firstName: 'ยงยุทธ', lastName: 'ชื่นชม', taxStatus: '' },
            { id: 'P5-003', rank: 'ส.ต.', firstName: 'ธนากรณ์', lastName: 'กระแสเทพ', taxStatus: '' },
            { id: 'P5-004', rank: 'ส.ต.', firstName: 'ชลชาติ', lastName: 'กองแก้ว', taxStatus: '' },
            { id: 'P5-005', rank: 'จ.ส.อ.(พ)', firstName: 'โยฆิน', lastName: 'แก้วเรือง', taxStatus: '' },
            { id: 'P5-006', rank: 'ส.อ.', firstName: 'จตุรานนท์', lastName: 'พลศรีราช', taxStatus: '' },
            { id: 'P5-007', rank: 'ร.ต.', firstName: 'โสภณ', lastName: 'ชื่นสุวรรณ', taxStatus: '' },
            { id: 'P5-008', rank: 'ส.อ.', firstName: 'วัชรพงษ์', lastName: 'หงษ์คำมี', taxStatus: '' },
            { id: 'P5-009', rank: 'จ.ส.อ.', firstName: 'นพดล', lastName: 'จุลศิริ', taxStatus: '' },
            { id: 'P5-010', rank: 'จ.ส.ท.', firstName: 'บุญส่ง', lastName: 'พลอามาตย์', taxStatus: '' },
            { id: 'P5-011', rank: 'ส.อ.', firstName: 'อานนท์', lastName: 'พันธุระ', taxStatus: '' },
            { id: 'P5-012', rank: 'จ.ส.อ.', firstName: 'ไพฑูรย์', lastName: 'แสงหิรัญ', taxStatus: '' },
            { id: 'P5-013', rank: 'จ.ส.อ.', firstName: 'สุพรรณ', lastName: 'บุตรดี', taxStatus: '' },
            { id: 'P5-014', rank: 'ส.อ.', firstName: 'พิฆเนศ', lastName: 'วังคีรี', taxStatus: '' },
            { id: 'P5-015', rank: 'ส.อ.', firstName: 'วีระยุทธ', lastName: 'ซังบุษบา', taxStatus: '' },
            { id: 'P5-016', rank: 'จ.ส.อ.', firstName: 'สวนนท์', lastName: 'มณีวรรณ', taxStatus: '' },
            { id: 'P5-017', rank: 'ส.อ.', firstName: 'สุริยพงศ์', lastName: 'สำราญมาก', taxStatus: '' },
            { id: 'P5-018', rank: 'ส.อ.', firstName: 'สมาน', lastName: 'ธรรมรักษ์', taxStatus: '' },
            { id: 'P5-019', rank: 'จ.ส.อ.(พ)', firstName: 'สายัน', lastName: 'สระบัว', taxStatus: '' },
            { id: 'P5-020', rank: 'จ.ส.อ.(พ)', firstName: 'ประธาน', lastName: 'บุญเพ็ญ', taxStatus: '' },
            { id: 'P5-021', rank: 'จ.ส.อ.', firstName: 'สมปอง', lastName: 'คงสวัสดิ์', taxStatus: '' },
            { id: 'P5-022', rank: 'ร.ต.', firstName: 'อภิชาติ', lastName: 'ทุมเที่ยง', taxStatus: '' },
            { id: 'P5-023', rank: 'จ.ส.อ.', firstName: 'สีหนาท', lastName: 'พลโดด', taxStatus: '' },
            { id: 'P5-024', rank: 'ส.อ.', firstName: 'ชาคร', lastName: 'ชิงหล้า', taxStatus: '' },
            { id: 'P5-025', rank: 'จ.ส.ท.', firstName: 'นพดล', lastName: 'ไกรหา', taxStatus: '' },
            { id: 'P5-026', rank: 'จ.ส.อ.(พ)', firstName: 'จตุรงค์', lastName: 'ภัทรรัตนานนท์', taxStatus: '' },
            { id: 'P5-027', rank: 'จ.ส.อ.', firstName: 'อรุณ', lastName: 'หมีแรต', taxStatus: '' },
            { id: 'P5-028', rank: 'จ.ส.อ.(พ)', firstName: 'อรรถพล', lastName: 'สว่างศรี', taxStatus: '' },
            { id: 'P5-029', rank: 'ส.อ.', firstName: 'ชุติวัติ', lastName: 'โพธิ์พระยา', taxStatus: '' },
            { id: 'P5-030', rank: 'ร.ต.', firstName: 'สุพรรณ', lastName: 'พันธุระ', taxStatus: '' },
            { id: 'P5-031', rank: 'จ.ส.อ.', firstName: 'สมใจ', lastName: 'เถาว์ทิพย์', taxStatus: '' },
            { id: 'P5-032', rank: 'จ.ส.อ.', firstName: 'อภิเชษฐ', lastName: 'วงษ์ศรีนาค', taxStatus: '' },
            { id: 'P5-033', rank: 'ส.อ.', firstName: 'ศรชัย', lastName: 'จำปาคำ', taxStatus: '' },
            { id: 'P5-034', rank: 'ส.อ.', firstName: 'อธิยุต', lastName: 'บรรณวาล', taxStatus: '' },
            { id: 'P5-035', rank: 'ส.อ.', firstName: 'อภิวัฒน์', lastName: 'พูดดี', taxStatus: '' },
            { id: 'P5-036', rank: 'จ.ส.ต.', firstName: 'ประกาศิต', lastName: 'เทียนคำ', taxStatus: '' },
            { id: 'P5-037', rank: 'ส.อ.', firstName: 'พิพัฒน์พล', lastName: 'รอดเล็ก', taxStatus: '' },
            { id: 'P5-038', rank: 'ส.อ.', firstName: 'วรรลภ', lastName: 'สัสดีทอง', taxStatus: '' },
            { id: 'P5-039', rank: 'ส.อ.', firstName: 'ภาคภูมิ', lastName: 'ฉลูทอง', taxStatus: '' },
            { id: 'P5-040', rank: 'จ.ส.อ.', firstName: 'เอกศักดิ์', lastName: 'ขวัญทอง', taxStatus: '' },
            { id: 'P5-041', rank: 'จ.ส.อ.', firstName: 'เอนก', lastName: 'โพธิ์ทอง', taxStatus: '' },
            { id: 'P5-042', rank: 'ส.อ.', firstName: 'นิรุตติ์', lastName: 'พูนผล', taxStatus: '' },
            { id: 'P5-043', rank: 'ส.อ.', firstName: 'สมพร', lastName: 'แก้วแจ่มศรี', taxStatus: '' },
            { id: 'P5-044', rank: 'ส.อ.', firstName: 'กุมภา', lastName: 'คำเถื่อน', taxStatus: '' },
            { id: 'P5-045', rank: 'ส.อ.', firstName: 'ชนินทร์', lastName: 'ดอกพวง', taxStatus: '' },
            { id: 'P5-046', rank: 'ส.อ.', firstName: 'ปิราวัตร', lastName: 'ดงทอง', taxStatus: '' },
            { id: 'P5-047', rank: 'จ.ส.อ.', firstName: 'ชัยรัตน์', lastName: 'จุดาบุตร', taxStatus: '' },
            { id: 'P5-048', rank: 'ส.ท.', firstName: 'จตุพล', lastName: 'พิลาพอง', taxStatus: '' },
            { id: 'P5-049', rank: 'ส.ท.', firstName: 'อาณาจักร', lastName: 'มูลดี', taxStatus: '' },
            { id: 'P5-050', rank: 'ส.ท.', firstName: 'ปองชัย', lastName: 'ทมินเหมย', taxStatus: '' },
            { id: 'P5-051', rank: 'จ.ส.อ.(พ)', firstName: 'ธีรศักดิ์', lastName: 'สิมาทอง', taxStatus: '' },
            { id: 'P5-052', rank: 'จ.ส.อ.(พ)', firstName: 'จิรายุ', lastName: 'ยี่โถหุ่น', taxStatus: '' },
            { id: 'P5-053', rank: 'ส.อ.', firstName: 'ธนธร', lastName: 'พืชสอน', taxStatus: '' },
            { id: 'P5-054', rank: 'จ.ส.อ.', firstName: 'วีรยุทธ', lastName: 'ดำเนิน', taxStatus: '' },
            { id: 'P5-055', rank: 'ส.อ.', firstName: 'ทักษิณ', lastName: 'ศิริเพชร', taxStatus: '' },
            { id: 'P5-056', rank: 'ส.ท.', firstName: 'จิรพัฒน์', lastName: 'ผ่องสติปัญญา', taxStatus: '' },
            { id: 'P5-057', rank: 'ส.ท.', firstName: 'สิทธินนท์', lastName: 'หวังเทียมกลาง', taxStatus: '' },
            { id: 'P5-058', rank: 'ส.ท.', firstName: 'ณัฐวุฒิ', lastName: 'ดีดน้อย', taxStatus: '' },
            { id: 'P5-059', rank: 'ส.อ.', firstName: 'สุริยะ', lastName: 'มีแย้ม', taxStatus: '' },
            { id: 'P5-060', rank: 'จ.ส.อ.', firstName: 'อภิวัฒน์', lastName: 'ธนะเวช', taxStatus: '' },
            { id: 'P5-061', rank: 'ส.อ.', firstName: 'ประเสริฐ', lastName: 'เติมชีพ', taxStatus: '' },
            { id: 'P5-062', rank: 'ส.อ.', firstName: 'ไพฑูรย์', lastName: 'บุญเงิน', taxStatus: '' },
            { id: 'P5-063', rank: 'จ.ส.อ.', firstName: 'ศักรินทร์', lastName: 'รักใคร่', taxStatus: '' },
            { id: 'P5-064', rank: 'ส.อ.', firstName: 'พีระยุทธ์', lastName: 'พุกยงค์', taxStatus: '' },
            { id: 'P5-065', rank: 'ส.อ.', firstName: 'วรวัฒน์', lastName: 'ไหวดี', taxStatus: '' },
            { id: 'P5-066', rank: 'จ.ส.อ.', firstName: 'ศิลา', lastName: 'บัวพลายจิต', taxStatus: '' },
            { id: 'P5-067', rank: 'ส.อ.', firstName: 'สมชัย', lastName: 'ขำเอี่ยม', taxStatus: '' },
            { id: 'P5-068', rank: 'จ.ส.อ.', firstName: 'ณวัสพล', lastName: 'แสนคำ', taxStatus: '' },
            { id: 'P5-069', rank: 'ส.อ.', firstName: 'ศราวุธ', lastName: 'พันธุ์บุญมี', taxStatus: '' },
            { id: 'P5-070', rank: 'จ.ส.อ.', firstName: 'อภินันชัย', lastName: 'ตั้งมั่น', taxStatus: '' },
            { id: 'P5-071', rank: 'จ.ส.อ.', firstName: 'อรรถสิทธิ์', lastName: 'จันทร์เพ็ง', taxStatus: '' },
            { id: 'P5-072', rank: 'จ.ส.อ.', firstName: 'สุทิน', lastName: 'แก้วอิ่ม', taxStatus: '' },
            { id: 'P5-073', rank: 'ส.อ.', firstName: 'นำชัย', lastName: 'สายสวาท', taxStatus: '' },
            { id: 'P5-074', rank: 'ส.ต.', firstName: 'ภราวุฒ', lastName: 'แสนสุข', taxStatus: '' },
            { id: 'P5-075', rank: 'ส.ต.', firstName: 'รุ่งพิชญ์', lastName: 'พรมปิง', taxStatus: '' },
            { id: 'P5-076', rank: 'ส.ต.', firstName: 'พรมนัส', lastName: 'นุชนงคราญ', taxStatus: '' }
        ]
    }
};
